# Generated by Django 3.1.3 on 2021-01-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('prix', models.CharField(blank=True, max_length=255, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'article',
                'managed': 'True',
            },
        ),
    ]
