# Generated by Django 3.0.5 on 2021-01-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='quantite',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
